blog/urls.py
from django.urls import path
from blog import views
urlpatterns=[

    path('register/', views.UserRegister,name="register" ),
    path('login/', views.UserLogin, name="login"),
    path('', views.Home, name="home"),
    path('logout/',views.UserLogout,name="logout"),
    path('profile/',views.Profile,name="profile"),
    path('post/',views.PostListView.as_view(),name='post_list'),
    path('post/drafts',views.PostDraftList.as_view(),name='post_draft_list'),
    path('post/<int:pk>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new',views.CreatePostView.as_view(),name='post_create'),
    path('post/update/<int:pk>',views.PostUpdateView.as_view(),name='post_update'),
    path('post/delete/<int:pk>',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/comment/<int:pk>', views.add_comment_to_post,name='add_comment'),
    path('post/newcomment/<int:pk>', views.add_new__comment_to_post,name='add_new_comment'),
    path('comment/approve/<int:pk>',views.comment_approve,name='comment_approve'),
    path('comment/remove/<int:pk>',views.comment_remove,name='comment_remove'),
    path('post/publish/<int:pk>', views.post_publish, name='post_publish'),
    path('dashboard/', views.Dashboard, name='dashboard'),


]

newproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

class Post(models.Model):
    author= models.ForeignKey(User, on_delete=models.CASCADE)
    title= models.CharField(max_length=200)
    text= models.TextField()
    created_date= models.DateTimeField(default= timezone.now)
    publish_date= models.DateTimeField(blank= True, null=True)

    @property
    def publish(self):
        self.publish_date = timezone.now()
        self.save()
        
    @property
    def approve_comments(self):
        return self.comments.filter(approved_comment=True)
    
    def get_absolute_url(self):
        return reverse("post_detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.title



class Comment(models.Model):
    post= models.ForeignKey(Post, on_delete =models.CASCADE, related_name='comments')
    author= models.CharField(max_length=200)
    text=models.TextField()
    created_date=  models.DateTimeField(default=timezone.now)
    approved_comment= models.BooleanField(default=False)

    @property
    def approve(self):
        self.approved_comment= True
        self.save()
 

    def __str__(self):
        return self.text

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
 
  <!-- <link rel="stylesheet" href="{% static 'css/home.css' %}"> -->
    {% block title%}
    {%endblock%}
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <ul class="nav navbar-nav ">
        <li>
          <a class="navbar-brand" href="\">
         
          Django <img src="{% static 'images/bootstrap-solid.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">Blogs
        </a>
        </li>
        
      <li>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </li>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            
            <a class="nav-item nav-link" href="{% url 'post_list' %}">Post</a>
            {% if user.is_staff %}
            <a class="nav-item nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            {% endif %}
            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
          </div>
          </div>
      </ul>
    
      <ul class="nav navbar-nav navbar-right " >
        <li>
          <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
        </li>
        {% if user.is_authenticated %}
        <li><a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a></li>
        <li>
          <a class="nav-item nav-link" href="{% url 'post_create' %}">New Post</a>
        </li>
        <li>
          <a class="nav-item nav-link" href="{% url 'post_draft_list' %}">Drafts</a>
        </li>
        {% else %}
        <li><a class="nav-item nav-link" href="{% url 'login' %}">Login</a></li>     
   {% endif %}
      </ul> 
     </div>
 
      </nav>
      
    <div class="container">
  {% block content%}

  {%endblock%}
    </div>

 {% block javascript%}

    {%endblock%}
</body>
</html>

templates/comment-form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
{% endblock %}

{% block content %}
<!-- <a href="https://github.com/yabwe/medium-editor" class="github-link"><img style="z-index: 100;position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a> -->
<h3> Post Form...</h3>
<form method="POST" >
{% csrf_token%}
{{form | crispy}}
<button type="submit" class="btn btn-primary">Save</button>
</form>

<!-- <script>var editor = new MediumEditor('.editable');</script>-->
<script>
   var editor = new MediumEditor('.editable', {
    toolbar: {
        buttons: [
            'bold',
            'italic',
            {
                name: 'h1',
                action: 'append-h2',
                aria: 'header type 1',
                tagNames: ['h2'],
                contentDefault: '<b>H1</b>',
                classList: ['custom-class-h1'],
                attrs: {
                    'data-custom-attr': 'attr-value-h1'
                }
            },
            {
                name: 'h2',
                action: 'append-h3',
                aria: 'header type 2',
                tagNames: ['h3'],
                contentDefault: '<b>H2</b>',
                classList: ['custom-class-h2'],
                attrs: {
                    'data-custom-attr': 'attr-value-h2'
                }
            },
            'justifyCenter',
            'quote',
            'anchor'
        ]
    }
});
</script>

{% endblock %}

templates/dash.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

<h3 class="text-success m-2">All Draft Post:</h3>
{% for post in posts %}

<div class="row m-4">
    <div class="col-md-8">
<h5><a href="{% url 'post_detail' post.pk  %}">  {{post.title}}</a> </h5>
    </div>
    <div class="col-md-2">
    <a class="btn btn-primary " href="{% url 'post_publish' post.pk  %}"> <small>Publish Post</small></a>
    </div>
    <div class="col-md-2">
        <a class="btn btn-primary " href="{% url 'post_publish' post.pk  %}"> <small>Remove Post</small></a>
    </div>
</div>
{% endfor %}


<h3 class="text-success m-2">All Draft Comment:</h3>
{% for comment in comments %}
<div class="row">
    <div class="card" style="width: 100%;">
        <div class="card-body">
          <h5 class="card-title text-primary">{{comment.author}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{comment.post}}</h6>
          <p class="card-text"> {{comment.text}}</p>
          <a href="{% url 'comment_approve' comment.id  %}" class="card-link">Publish Comment</a>
          <a href="{% url 'comment_remove' comment.pk  %}" class="card-link">Publish Remove</a>
        </div>
      </div>

</div>
{% endfor %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}
{% endblock %}

{% block content %}
<h3 class="m-4 text-primary" > Welcome Django Blog where You can find all kinds of code and tips about Django </h3>
<h3 class="text-success m-2"> Some Recent Posts</h3>


<div class="row flex ">
  {% for post in posts %}
  <div  class="col-lg-4 d-flex align-items-stretch" style="margin-bottom:10px;">
<div class="card-deck"  >
  <div class="card h-100 ">
    <img  src="{% static 'images/sample.jpg' %}" style="width: auto;height:auto" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><a href="{% url 'post_detail' post.pk  %}">  {{post.title}} </a></h5>
      <p class="card-text">{{post.text }}.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Post Created at {{ post.publish_date | naturaltime}}</small>
    </div>
  </div>
</div>
</div>
{% endfor %}
</div>


<div class="m-2">
    {% if posts.has_other_pages %}
      <ul class="pagination">
        {% if posts.has_previous %}
          <li class="page-item"> <a class="page-link"  href="?page={{ posts.previous_page_number }}">Previous</a></li>
        {% else %}
          <li  class="page-item disabled"><span class="page-link"  >Previous</span></li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
          {% if posts.number == i %}
            <li class=" page-item active"><span class="page-link" >{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li class="page-item"><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if posts.has_next %}
          <li class="page-item"><a class="page-link"  href="?page={{ posts.next_page_number }}">Next</a></li>
        {% else %}
          <li class=" page-item disabled"><span class="page-link"  >Next</span></li>
        {% endif %}
      </ul>
    {% endif %}
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block title%}
<title>Login</title>
{%endblock%}

{%block content%}

<h3>Login here..</h3>
<br>
{% if messages %}
{% for msg in messages %}

<div class="alert " role="alert">
  
 {{msg}}
 
</div>
{% endfor %}
{% endif %}
<form method="POST" action="">
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input name="username" value="{{ values.username }}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required>
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input name="password" type="password" class="form-control" id="exampleInputPassword1" required>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

templates/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="container">
<h3>Post: {{post.title}}</h3>
<strong class=" text-primary mb-2">Posted by @ {{post.author}}</strong>
<p>Summary: {{post.text|safe|linebreaksbr}}</p>

{% if user.is_staff  %}

<button class="btn btn-primary"><a class="btn-primary" href="{% url 'post_update' post.pk  %}"> Update</a></button>

<button class="btn btn-danger"> <a class="btn-danger" href="{% url 'post_delete' post.pk  %}"> Delete</a></button>

<button class="btn btn-secondary"> <a class="btn-secondary" href="{% url 'add_comment' post.pk  %}"> Comment</a></button>

{% if post.publish_date is None %}
<button class="btn btn-success"> <a class="btn-success " href="{% url 'post_publish' post.pk  %}"> Publish</a></button>
{% endif %}

{% endif %}

<br>
<div class="row">
    <div class="col">
        <form  method="POST" action="{% url 'add_new_comment' post.pk %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_text">Comment here..</label>
                <textarea class="form-control" name="text" id="id_text" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>

<hr>
{% for comment in post.comments.all %}
<br>
    {% if user.is_staff or comment.approved_comment %}
            {{ comment.created_date }}

            {% if not comment.approved_comment %}

            <button class="btn btn-primary"> <a class="btn-primary" href="{% url 'comment_approve' comment.pk  %}"> Approve</a></button>

            <button class="btn btn-success"> <a class="btn-success" href="{% url 'comment_remove' comment.pk  %}"> Remove</a></button>
            {% endif %}

        <p>{{ comment.text|safe|linebreaks }}</p>
        <p>Posted by: <strong> @{{ comment.author }}</strong></p>

    {% endif %}
{% empty %}
    <p>No comments posted.</p>
{% endfor %}

</div>
{% endblock %}

templates/post_draft_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<h3>Draft List</h3>

 {% for post in post_list %}
  <div class="container">
  <h3> <a href="{% url 'post_detail' post.pk  %}">  {{post.title}}</a> </h3>
  <p>{{post.text}}</p>
  </div>

 {% endfor %}

{% endblock %}

templates/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
{% endblock %}

{% block content %}
<h3> Post Form...</h3>
<form method="POST" >
{% csrf_token%}
{{form | crispy}}
<button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

templates/post_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
{% endblock %}

{% block content %}
<h3>Post List..</h3>

 {% for post in post_list %}
  <div class="container">
  <h3> <a href="{% url 'post_detail' post.pk  %}">  {{post.title}}</a> </h3>
  <p>{{post.text }}</p>
  </div>

 {% endfor %}

{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<br>
<h3>Welcome {{request.user}}</h3>

<h4>All Post:</h4>
{% for post in posts %}
<br>
<div class="row">
  <div class="col-10">
     <ul class="list-group m-2">
    <li class="list-group-item disabled" aria-disabled="true"> <strong>{{post.title}}</strong>  </li>
    <li class="list-group-item">{{post.text}}</li>
    <li class="list-group-item">Creation Date: {{post.created_date}} 
      <button class="btn btn-primary"><a class="btn-primary" href="{% url 'post_update' post.pk  %}"> Update</a></button>
      <button class="btn btn-danger"> <a class="btn-danger" href="{% url 'post_delete' post.pk  %}"> Delete</a></button>
    </li>
  </ul>
  </div>
 


</div>

{% endfor %}
{% endblock %}

templates/register.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{%block title%}
<title>Register</title>
{%endblock%}


{%block content%}
 <h3>Register Here...</h3>
<form method="POST" action="">
    {% csrf_token %}
    {{form|crispy }}
    
    <button class="btn btn-primary" type="submit">Register</button>
</form>
{% endblock %}